### ISSUE TITLE
What is the roadmap of ngMeetups

### ISSUE THREAD

**Issue by andela-jomadoye** [kingisaac95/ngmeetups#1]
Please fix the readme of this repo, the readme should contain information about the stack the application is intended to be build upon, and also how interested users can contribute to the application.

**Comment by kingisaac95** [comment]
The roadmap is in the works. Details about this project and it's development track will be uploaded here soon. Please kindly tell us if you have anymore concerns or would be interested to work woth us in this project. Thanks
